### ISSUE TITLE
Error when trying to validate openapi spec file

### ISSUE THREAD

**Issue by exu** [nwestfall/openapi-action#3]
Hello, 

Got error when trying to validate open api spec file: 

```
Warning: Unexpected input(s) 'file', valid inputs are ['github_token']
Run nwestfall/openapi-action@v1.0.1
(node:8963) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'value' of undefined
    at getAstNodeByPointer (/home/runner/work/_actions/nwestfall/openapi-action/v1.0.1/dist/index.js:2454:34)
    at getLineColLocation (/home/runner/work/_actions/nwestfall/openapi-action/v1.0.1/dist/index.js:2393:21)
    at exec (/home/runner/work/_actions/nwestfall/openapi-action/v1.0.1/dist/index.js:2490:22)
(node:8963) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8963) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Error can be seen here https://github.com/kubeshop/testkube/runs/4005995628?check_suite_focus=true 

Action is configured as follows: 

```
    - name: OpenAPI Lint Checks
      uses: nwestfall/openapi-action@v1.0.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        file: api/v1/testkube.yaml

```

(or here is path to file: https://github.com/kubeshop/testkube/blob/dcdb3d55ef9eeb30d36716a9c950efa7c0720dfe/.github/workflows/test.yml ) 

What should I configure to make it work ?
